<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\projetoNette\projetoNette\app\Presentation\Home/default.latte */
final class Template_55366d44d5 extends Latte\Runtime\Template
{
	public const Source = 'C:\\xampp\\htdocs\\projetoNette\\projetoNette\\app\\Presentation\\Home/default.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo 'ola mundo!  ';
	}
}
